name: OKR 2 - fase 0
run-name: Compute general OKR

on:
  workflow_call:
    # without output

jobs:
  generate-inputs-fase0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
      - name: Execute grep command
        run: |
          grep -r -n ".plt." --include="*.py" templates > charts_query.txt
      - name: Execute python script to identify shimoku chart
        run: python script/rex_plt_shimoku.py
      - name: Execute python script to identify all the available charts
        run: python script/cloud_shimoku.py
      - name: Execute python script to compute OBJ-1 OKR-2
        run: python script/OKR-2.py
      - name: Upload charts name SDK file
        uses: actions/upload-artifact@v3
        with:
          name: charts_data
          path: |
            OBJ-1_KR-2.csv
            charts_frequency.csv
